name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@v1.12.0

      env:
        HUGO_VERSION: 0.69.1
        TARGET_REPO: uasdqa/uasdqa.github.io
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CNAME: www.uasdqa.me
        HUGO_ARGS: --debug
